Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/xenial64"
	config.vm.provision :shell, path: "bootstrap.sh"
	config.vm.synced_folder '../', '/vagrant'
	config.vm.network "forwarded_port", guest: 80, host: 8081
	config.vm.provider "virtualbox" do |v|
		v.name = "vagrant-base"
		v.memory = 4096
		v.cpus = 2
	end
end
