# -*- mode: ruby -*-
# vi: set ft=ruby :

#BOX_IMAGE = "ubuntu/xenial64"
BOX_IMAGE = "centos/7"
BOX_URL = "http://cloud.centos.org/centos/7/vagrant/x86_64/images/CentOS-7.box"

Vagrant.configure("2") do |config|

	bootstrap_script = <<-SHELL
#               apt-get update
                echo "
                10.2.2.10 ubuntu1
                10.2.2.11 ubuntu2
                10.2.2.12 ubuntu3
                " | sudo tee -a /etc/hosts
        SHELL

	nodes = [
		{ name: "ubuntu1", ip: "10.2.2.10" },
		{ name: "ubuntu2", ip: "10.2.2.11" },
		{ name: "ubuntu3", ip: "10.2.2.12" }
	]

	nodes.each do |node|
		config.vm.define "#{node[:name]}" do |subconfig|
			subconfig.vm.hostname = node[:name]
			subconfig.vm.box = BOX_IMAGE
	                subconfig.vm.box_url = BOX_URL
	                subconfig.vm.network "private_network", ip: "#{node[:ip]}"
		end
	end

	config.vm.provider "virtualbox" do |vb|
		vb.memory = 2048
		vb.cpus = 1
        end

	config.vm.provision "shell", inline: bootstrap_script

	config.vm.synced_folder '../', '/vagrant'

end
